# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e81f9d8a7c78322730aa89981e407a3edab982203257d1afacbceb7c1b9af9305c073439c50bca2e05e570ee83881502728917ee0f44f383eedd36e786e8f2

test:
  secret_key_base: b87dd56c56c4671f709dc0269248752dd7a5a87978e761e1fb1f72a5eb2c3535d72c80270b36674e79ba3a1bb2cf1dc9f8613a73980d1f7347e938537a3d00c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
